apiVersion: apps/v1
kind: Deployment
metadata:
 name: salao-api
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
     app: salao-api
 template:
   metadata:
     labels:
       app: salao-api
   spec:
     containers:
     - name: salao-api
       image: seu-registry/salao-api:1.0.0
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8080
       env:
       - name: SPRING_PROFILES_ACTIVE
         value: "prod"
       - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
         value: "http://192.168.18.200:8080/realms/salao-realm"
       - name: SPRING_DATASOURCE_URL
         value: "jdbc:postgresql://postgres-service:5432/salao_db"
---
apiVersion: v1
kind: Service
metadata:
 name: salao-api-service
spec:
 type: ClusterIP
 selector:
   app: salao-api
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
